//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K9.Base.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K9.Base.Globalisation.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activated.
        /// </summary>
        public static string AccountActivated {
            get {
                return ResourceManager.GetString("AccountActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was activated successfully..
        /// </summary>
        public static string AccountActivatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account could not be activated..
        /// </summary>
        public static string AccountActivationFailed {
            get {
                return ResourceManager.GetString("AccountActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string AccountActivationTitle {
            get {
                return ResourceManager.GetString("AccountActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has already been activated..
        /// </summary>
        public static string AccountAlreadyActivated {
            get {
                return ResourceManager.GetString("AccountAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was created successfully..
        /// </summary>
        public static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted. We&apos;re sad to see you go!.
        /// </summary>
        public static string AccountDeleteSuccess {
            get {
                return ResourceManager.GetString("AccountDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been locked.
        /// </summary>
        public static string AccountLockedError {
            get {
                return ResourceManager.GetString("AccountLockedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of consecutive log-in failures exceeded the maximum allowed..
        /// </summary>
        public static string AccountLockedErrorDetails {
            get {
                return ResourceManager.GetString("AccountLockedErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string AccountLockedTitle {
            get {
                return ResourceManager.GetString("AccountLockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not yet been activated. Please check your email and follow the link to activate your account..
        /// </summary>
        public static string AccountNotActivatedError {
            get {
                return ResourceManager.GetString("AccountNotActivatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details have been successfully updated..
        /// </summary>
        public static string AccountUpdatedSuccess {
            get {
                return ResourceManager.GetString("AccountUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Account.
        /// </summary>
        public static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While using this site, you agree to have read and accepted our terms of use, cookie and privacy policy.
        /// </summary>
        public static string AgreeToTerms {
            get {
                return ResourceManager.GetString("AgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Information.
        /// </summary>
        public static string AuditInformation {
            get {
                return ResourceManager.GetString("AuditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings.
        /// </summary>
        public static string Blessings {
            get {
                return ResourceManager.GetString("Blessings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string BodyLabel {
            get {
                return ResourceManager.GetString("BodyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent you an email with a link to activate your account..
        /// </summary>
        public static string CheckAccountActivationEmail {
            get {
                return ResourceManager.GetString("CheckAccountActivationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Services.
        /// </summary>
        public static string ClientServices {
            get {
                return ResourceManager.GetString("ClientServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact support.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was received. Thank you!.
        /// </summary>
        public static string ContactSupportSuccess {
            get {
                return ResourceManager.GetString("ContactSupportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsTitle {
            get {
                return ResourceManager.GetString("ContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string CountryDefiniteArticle {
            get {
                return ResourceManager.GetString("CountryDefiniteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string CountryIndefiniteArticle {
            get {
                return ResourceManager.GetString("CountryIndefiniteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string CreatedOnLabel {
            get {
                return ResourceManager.GetString("CreatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string CurrentPasswordCorrectNewInvalidError {
            get {
                return ResourceManager.GetString("CurrentPasswordCorrectNewInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMMM yyyy.
        /// </summary>
        public static string DateLongFormat {
            get {
                return ResourceManager.GetString("DateLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact support..
        /// </summary>
        public static string DefaultAuthError {
            get {
                return ResourceManager.GetString("DefaultAuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string DefiniteArticleWithApostrophe {
            get {
                return ResourceManager.GetString("DefiniteArticleWithApostrophe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to delete your account.
        /// </summary>
        public static string DeleteAccountFailed {
            get {
                return ResourceManager.GetString("DeleteAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record cannot be deleted as its foreign key exists in other tables..
        /// </summary>
        public static string DeleteConflictError {
            get {
                return ResourceManager.GetString("DeleteConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete My Account.
        /// </summary>
        public static string DeleteMyAccount {
            get {
                return ResourceManager.GetString("DeleteMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Details.
        /// </summary>
        public static string DetailsText {
            get {
                return ResourceManager.GetString("DetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} with {2} {3} &apos;{4}&apos; already exists..
        /// </summary>
        public static string DuplicateIndexError {
            get {
                return ResourceManager.GetString("DuplicateIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddressLabel {
            get {
                return ResourceManager.GetString("EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is unavailable..
        /// </summary>
        public static string EmailIsUnavailableError {
            get {
                return ResourceManager.GetString("EmailIsUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note, the email is valid for 24 hours only..
        /// </summary>
        public static string EmailValidFor {
            get {
                return ResourceManager.GetString("EmailValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment.
        /// </summary>
        public static string Enrollment {
            get {
                return ResourceManager.GetString("Enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string FeminieDefiniteArticle {
            get {
                return ResourceManager.GetString("FeminieDefiniteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string FeminineIndefiniteArticle {
            get {
                return ResourceManager.GetString("FeminineIndefiniteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files selected.
        /// </summary>
        public static string FilesSelected {
            get {
                return ResourceManager.GetString("FilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        public static string ForgottenPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgottenPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are having a few problems processing your request. Please try again later..
        /// </summary>
        public static string FriendlyErrorMessage {
            get {
                return ResourceManager.GetString("FriendlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string GetInTouchTitle {
            get {
                return ResourceManager.GetString("GetInTouchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to the home page.
        /// </summary>
        public static string GoBackHome {
            get {
                return ResourceManager.GetString("GoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Us.
        /// </summary>
        public static string HelpUs {
            get {
                return ResourceManager.GetString("HelpUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iboga.
        /// </summary>
        public static string Iboga {
            get {
                return ResourceManager.GetString("Iboga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account.
        /// </summary>
        public static string IfNoAccount {
            get {
                return ResourceManager.GetString("IfNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageLabel {
            get {
                return ResourceManager.GetString("ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0} {1}.
        /// </summary>
        public static string InTimespan {
            get {
                return ResourceManager.GetString("InTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidEmailError {
            get {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password..
        /// </summary>
        public static string InvalidPasswordEnteredError {
            get {
                return ResourceManager.GetString("InvalidPasswordEnteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidPasswordRetreivalError {
            get {
                return ResourceManager.GetString("InvalidPasswordRetreivalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidRetrievalQuestionError {
            get {
                return ResourceManager.GetString("InvalidRetrievalQuestionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check and try again..
        /// </summary>
        public static string InvalidUsernameError {
            get {
                return ResourceManager.GetString("InvalidUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string IsDeletedLabel {
            get {
                return ResourceManager.GetString("IsDeletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Mail.
        /// </summary>
        public static string IsUnsubscribedLabel {
            get {
                return ResourceManager.GetString("IsUnsubscribedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string LastUpdatedByLabel {
            get {
                return ResourceManager.GetString("LastUpdatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated On.
        /// </summary>
        public static string LastUpdatedOnLabel {
            get {
                return ResourceManager.GetString("LastUpdatedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log into your account..
        /// </summary>
        public static string LogIntoYourAccount {
            get {
                return ResourceManager.GetString("LogIntoYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account..
        /// </summary>
        public static string LogIntoYourExternalAccount {
            get {
                return ResourceManager.GetString("LogIntoYourExternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LogInVerb {
            get {
                return ResourceManager.GetString("LogInVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using another service..
        /// </summary>
        public static string LogInWithOtherService {
            get {
                return ResourceManager.GetString("LogInWithOtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string MasculineDefiniteArticle {
            get {
                return ResourceManager.GetString("MasculineDefiniteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string MasculineIndefiniteArticle {
            get {
                return ResourceManager.GetString("MasculineIndefiniteArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Direction.
        /// </summary>
        public static string MessageDirectionLabel {
            get {
                return ResourceManager.GetString("MessageDirectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete My Account.
        /// </summary>
        public static string MyAccountDeleteAccount {
            get {
                return ResourceManager.GetString("MyAccountDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string MyAccountDeleteConfirm {
            get {
                return ResourceManager.GetString("MyAccountDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccountTitle {
            get {
                return ResourceManager.GetString("MyAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string NewPasswordMatchError {
            get {
                return ResourceManager.GetString("NewPasswordMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Item.
        /// </summary>
        public static string NewsItem {
            get {
                return ResourceManager.GetString("NewsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Items.
        /// </summary>
        public static string NewsItems {
            get {
                return ResourceManager.GetString("NewsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are looking for cannot be found. It may have been removed, had its name changed, or is temporarily unavailable..
        /// </summary>
        public static string NotFoundError {
            get {
                return ResourceManager.GetString("NotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something&apos;s missing.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string OfPreposition {
            get {
                return ResourceManager.GetString("OfPreposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string OfPrepositionWithApostrophe {
            get {
                return ResourceManager.GetString("OfPrepositionWithApostrophe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of The Forest.
        /// </summary>
        public static string OfTheForest {
            get {
                return ResourceManager.GetString("OfTheForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On The Brink Of Extinction.
        /// </summary>
        public static string OnTheBrinkOfExtinctionTitle {
            get {
                return ResourceManager.GetString("OnTheBrinkOfExtinctionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Latest Pictures.
        /// </summary>
        public static string OurLatestPicturesTitle {
            get {
                return ResourceManager.GetString("OurLatestPicturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string OurMission {
            get {
                return ResourceManager.GetString("OurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission Statement &amp; Aims.
        /// </summary>
        public static string OurMissionTitle {
            get {
                return ResourceManager.GetString("OurMissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Partners.
        /// </summary>
        public static string OurPartners {
            get {
                return ResourceManager.GetString("OurPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string PasswordHasChangedConfirmation {
            get {
                return ResourceManager.GetString("PasswordHasChangedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordMatchError {
            get {
                return ResourceManager.GetString("PasswordMatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordMinLengthError {
            get {
                return ResourceManager.GetString("PasswordMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        public static string PasswordResetConfirmation {
            get {
                return ResourceManager.GetString("PasswordResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Your password has been reset. Please [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PasswordResetEmail {
            get {
                return ResourceManager.GetString("PasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve sent you an email with a link to reset your password..
        /// </summary>
        public static string PasswordResetEmailSent {
            get {
                return ResourceManager.GetString("PasswordResetEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to reset your password..
        /// </summary>
        public static string PasswordResetFailError {
            get {
                return ResourceManager.GetString("PasswordResetFailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string PasswordResetTitle {
            get {
                return ResourceManager.GetString("PasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string PasswordSetConfirmation {
            get {
                return ResourceManager.GetString("PasswordSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string PermissionLabel {
            get {
                return ResourceManager.GetString("PermissionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        public static string PhoneNumberLabel {
            get {
                return ResourceManager.GetString("PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please email our support team for further information..
        /// </summary>
        public static string PleaseContactSupport {
            get {
                return ResourceManager.GetString("PleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one of the following:.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power User.
        /// </summary>
        public static string PowerUser {
            get {
                return ResourceManager.GetString("PowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please try again..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published By.
        /// </summary>
        public static string PublishedByLabel {
            get {
                return ResourceManager.GetString("PublishedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published On.
        /// </summary>
        public static string PublishedOnLabel {
            get {
                return ResourceManager.GetString("PublishedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permissions.
        /// </summary>
        public static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string SentByUserLabel {
            get {
                return ResourceManager.GetString("SentByUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent On.
        /// </summary>
        public static string SentOnLabel {
            get {
                return ResourceManager.GetString("SentOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To.
        /// </summary>
        public static string SentToUserLabel {
            get {
                return ResourceManager.GetString("SentToUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortly.
        /// </summary>
        public static string Shortly {
            get {
                return ResourceManager.GetString("Shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///        padding: 0;
        ///        font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///        font-size: 100%;
        ///        text-rendering: optimizeLegibility !important;
        ///        -webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///&lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///&lt;p class=&quot;text&quot;&gt;Thank you for  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SupportQuery {
            get {
                return ResourceManager.GetString("SupportQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Us!.
        /// </summary>
        public static string SupportUs {
            get {
                return ResourceManager.GetString("SupportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Standard.
        /// </summary>
        public static string SystemStandard {
            get {
                return ResourceManager.GetString("SystemStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Letter Country Code.
        /// </summary>
        public static string ThreeLetterCountryCodeLabel {
            get {
                return ResourceManager.GetString("ThreeLetterCountryCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ago.
        /// </summary>
        public static string TimespanAgo {
            get {
                return ResourceManager.GetString("TimespanAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0} {1}.
        /// </summary>
        public static string TimespanFuture {
            get {
                return ResourceManager.GetString("TimespanFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Letter Country Code.
        /// </summary>
        public static string TwoLetterCountryCodeLabel {
            get {
                return ResourceManager.GetString("TwoLetterCountryCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view the requested resource..
        /// </summary>
        public static string UnauthorizedError {
            get {
                return ResourceManager.GetString("UnauthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string UnsuccessfulLoginServiceError {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to update your password..
        /// </summary>
        public static string UpdatePaswordError {
            get {
                return ResourceManager.GetString("UpdatePaswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Your Details.
        /// </summary>
        public static string UpdateYourDetails {
            get {
                return ResourceManager.GetString("UpdateYourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded On.
        /// </summary>
        public static string UploadedOnLabel {
            get {
                return ResourceManager.GetString("UploadedOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That email address already is already in use. Please enter a different one..
        /// </summary>
        public static string UserNameEmailExistsError {
            get {
                return ResourceManager.GetString("UserNameEmailExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string UsernameExistsError {
            get {
                return ResourceManager.GetString("UsernameExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is unavailable..
        /// </summary>
        public static string UsernameIsUnavailableError {
            get {
                return ResourceManager.GetString("UsernameIsUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UsernamePasswordIncorrectError {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not exist.
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact support..
        /// </summary>
        public static string UserRejectedError {
            get {
                return ResourceManager.GetString("UserRejectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;{Title}&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///    html
        ///    {
        ///        margin: 0;
        ///		padding: 0;
        ///		font-family: &quot;Segoe UI&quot; , Verdana, Helvetica, Sans-Serif;
        ///		font-size: 100%;
        ///		text-rendering: optimizeLegibility !important;
        ///		-webkit-font-smoothing: antialiased !important;
        ///        margin: 0; 
        ///        color: #333;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Dear {FirstName},&lt;/p&gt;
        ///    &lt;p class=&quot;text&quot;&gt;Thank you for registering with {Comp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeEmail {
            get {
                return ResourceManager.GetString("WelcomeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
